# main links
main:
  - title: "카테고리"
    url: /categories/
  - title: "태그"
    url: /tags/
  - title: "검색"
    url: /search/

docs:
  - title: "@>---"
    children:
      - title: "카테고리"
        url: /categories/
      - title: "태그"
        url: /tags/

views:
  - title: "카테고리"
    use: true

  # - title: "About"
  #   url: https://mmistakes.github.io/minimal-mistakes/about/
  # - title: "Sample Posts"
  #   url: /year-archive/
  # - title: "Sample Collections"
  #   url: /collection-archive/
  # - title: "Sitemap"
  #   url: /sitemap/